services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      
    volumes:
      -  mongodata:/data/db
      - ./mongodb/config:/data/configdb
    
    # Authentication environment variables removed

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
    driver: local