"""v

Revision ID: f62ee13a5506
Revises: 
Create Date: 2025-06-08 07:37:27.983578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f62ee13a5506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=False),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('asset_project_id_index', 'assets', ['asset_project_id'], unique=False)
    op.create_index('asset_type_index', 'assets', ['asset_type'], unique=False)
    op.create_table('data_chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_project_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['chunk_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunk_asset_id', 'data_chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_project_id', 'data_chunks', ['chunk_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_project_id', table_name='data_chunks')
    op.drop_index('ix_chunk_asset_id', table_name='data_chunks')
    op.drop_table('data_chunks')
    op.drop_index('asset_type_index', table_name='assets')
    op.drop_index('asset_project_id_index', table_name='assets')
    op.drop_table('assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
